[parity]
mode="active"
chain = "ropsten"
base_path = "./ropsten"
db_path = "./ropsten/chains"
keys_path = "./ropsten/keys"
identity = "tinycalf"
light = false
no_persistent_txqueue = true

[rpc]
disable = false
port = 8545
interface = "local"
cors = ["null"]
apis = ["all"]
hosts = ["none"]
server_threads = 10

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["all"]
apis = ["all"]
hosts = ["none"]

[network]
port = 30303
min_peers = 2
max_peers = 100
id = 3
bootnodes = [
"enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303",
"enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303",
]
reserved_peers = "./chains/ropstenpeers.txt"
reserved_only = true
