[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
# auto_update_delay = 200
# auto_update_check_frequency = 50
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false
chain = "./chains/tinycalf.json"
base_path = "./data"
db_path = "./data/chains"
keys_path = "./data/keys"
identity = "tinycalf"
light = false
# no_hardcoded_sync = false

[rpc]
disable = false
port = 8545
interface = "local"
cors = ["null"]
apis = ["all"]
hosts = ["all"]
server_threads = 10



[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["all"]
hosts = ["all"]



[mining]
author = "0x08c43cd1d03dcce9ffe138165d5bb471e35b28b5"
engine_signer = "0x08c43cd1d03dcce9ffe138165d5bb471e35b28b5"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 2000
reseal_max_period = 10000
work_queue_size = 20
relay_set = "cheap"
min_gas_price = 20000000000
usd_per_tx = "0.0001"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_queue_gas = "off"
tx_queue_strategy = "gas_factor"
tx_queue_ban_count = 1
tx_queue_ban_time = 180
tx_gas_limit = "6283184"
tx_time_limit = 100
extra_data = "Parity"
remove_solved = false
notify_work = ["http://localhost:3001"]
refuse_service_transactions = false


[network]
# port = 30303
min_peers = 0
max_peers = 50
# nat = "any"
# id = 1
# bootnodes = []
# discovery = true
# warp = true
# allow_ips = "all"
# snapshot_peers = 0
# max_pending_peers = 64
# no_serve_light = false
# reserved_only = false
# reserved_peers = "./path_to_file"


[account]
unlock = ["0x08c43cd1d03dcce9ffe138165d5bb471e35b28b5"]
password = ["pass"]
keys_iterations = 10240
